import type { AppProps, AppType } from "next/app";
import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

import "~/styles/globals.css";
import GeneralLayout from "~/components/Layouts/GeneralLayout";

// might in some way mess with t3 bootstrapping, be wary
type ComponentWithPageLayout = AppProps & {
  Component: AppProps["Component"] & {
    PageLayout?: React.ComponentType;
  };
};

function MyApp({ Component, pageProps }: ComponentWithPageLayout) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      appearance={{
        variables: {
          colorPrimary: "rgb(236, 72, 153)",
          colorInputBackground: "rgb(253, 242, 248)",
          colorTextSecondary: "rgb(219, 39, 119)",
          fontFamily: "'Noto Sans', sans-serif",
          borderRadius: "0.375rem",
          colorDanger: "rgb(220, 38, 38)",
          colorSuccess: "rgb(22, 163, 74)",
          colorInputText: "rgb(157, 23, 77)",
          colorBackground: "rgb(253, 242, 248)",
          colorText: "rgb(157, 23, 77)",
          colorAlphaShade: "rgb(131, 24, 67)",
        },
      }}
      {...pageProps}
    >
      <Head>
        {/* prob want this to be dynamic eventually? 
        if not completely replace with "Explore" or "Create" or "Edit" or the title of the tab
        you are viewing, etc. then also add "- Tabsly"? */}
        <title>Autostrum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <GeneralLayout>
        {Component.PageLayout ? (
          <Component.PageLayout>
            <Component {...pageProps} />
          </Component.PageLayout>
        ) : (
          <Component {...pageProps} />
        )}
      </GeneralLayout>
    </ClerkProvider>
  );
}

export default api.withTRPC(MyApp);
