import type { AppProps, AppType } from "next/app";
import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

import "~/styles/globals.css";
import GeneralLayout from "~/components/Layouts/GeneralLayout";

// might in some way mess with t3 bootstrapping, be wary
type ComponentWithPageLayout = AppProps & {
  Component: AppProps["Component"] & {
    PageLayout?: React.ComponentType;
  };
};

function MyApp({ Component, pageProps }: ComponentWithPageLayout) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "rgb(236, 72, 153)",
          colorInputBackground: "rgb(253, 242, 248)",
          colorTextSecondary: "rgb(190, 24, 93)",
          colorInputText: "rgb(157, 23, 77)",
          colorBackground: "rgb(253, 242, 248)",
          colorText: "rgb(157, 23, 77)",
          colorAlphaShade: "rgb(131, 24, 67)",
        },
      }}
      {...pageProps}
    >
      <Head>
        {/* prob want this to be dynamic eventually? 
        if not completely replace with "Explore" or "Create" or "Edit" or the title of the tab
        you are viewing, etc. then also add "- Tabsly"? */}
        <title>Tabsly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GeneralLayout>
        {Component.PageLayout ? (
          <Component.PageLayout>
            <Component {...pageProps} />
          </Component.PageLayout>
        ) : (
          <Component {...pageProps} />
        )}
      </GeneralLayout>
    </ClerkProvider>
  );
}

export default api.withTRPC(MyApp);
