import { type AppType } from "next/app";
import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

import "~/styles/globals.css";
import Layout from "~/components/Layout/Layout";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "rgb(236, 72, 153)",
          colorInputBackground: "rgb(253, 242, 248)",
          colorTextSecondary: "rgb(190, 24, 93)",
          colorInputText: "rgb(157, 23, 77)",
          colorBackground: "rgb(253, 242, 248)",
          colorText: "rgb(157, 23, 77)",
          colorAlphaShade: "rgb(131, 24, 67)",
        },
      }}
      {...pageProps}
    >
      <Head>
        <title>Tabsly</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
