import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourcePath = join(__dirname, "../src/utils/updateCSSThemeVars.ts");
const outputPath = join(__dirname, "../src/styles/theme-tokens.css");

function loadExportedObject(source, exportName, endMarker) {
  const marker = `export const ${exportName} = `;
  const start = source.indexOf(marker);
  const end = source.indexOf(endMarker, start);

  if (start === -1 || end === -1) {
    throw new Error(`Could not locate ${exportName} in updateCSSThemeVars.ts`);
  }

  const objectLiteral = source
    .slice(start + marker.length, end + 1)
    .replace(/\/\/.*$/gm, "");

  // Plain object literal of string tokens.
  return Function(`"use strict"; return (${objectLiteral});`)();
}

function generateThemeTokensCSS(colorValues, screenshotColors) {
  const lines = [
    "/* Generated by scripts/generateThemeTokensCSS.mjs — do not edit by hand. */",
    "/* Source of truth: COLOR_VALUES + SCREENSHOT_COLORS in updateCSSThemeVars.ts */",
    "",
    'html[data-theme="light"] {',
    "  color-scheme: light;",
    "}",
    "",
    'html[data-theme="dark"] {',
    "  color-scheme: dark;",
    "}",
    "",
    /* Overlay alpha for GridTabCard color wash; scoped by data-theme so
       screenshot wrappers can override independently of <html>. */
    '[data-theme="light"] {',
    "  --screenshot-color-overlay-alpha: 0.7;",
    "}",
    "",
    '[data-theme="dark"] {',
    "  --screenshot-color-overlay-alpha: 0.35;",
    "}",
    "",
  ];

  for (const [color, themes] of Object.entries(colorValues)) {
    for (const [theme, tokens] of Object.entries(themes)) {
      // Attribute selector (not html-only) so screenshot preview wrappers can
      // scope maple/light|dark independently of the page theme.
      lines.push(`[data-color="${color}"][data-theme="${theme}"] {`);

      for (const [token, value] of Object.entries(tokens)) {
        lines.push(`  --${token}: ${value};`);
      }

      const screenshotTokens = screenshotColors[color]?.[theme];
      if (screenshotTokens) {
        for (const [token, value] of Object.entries(screenshotTokens)) {
          lines.push(`  --${token}: ${value};`);
        }
      }

      lines.push("}", "");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

const source = readFileSync(sourcePath, "utf8");
const colorValues = loadExportedObject(
  source,
  "COLOR_VALUES",
  "} as const satisfies ColorValues;",
);
const screenshotColors = loadExportedObject(
  source,
  "SCREENSHOT_COLORS",
  "} as const satisfies ScreenshotColorValues;",
);
const css = generateThemeTokensCSS(colorValues, screenshotColors);
writeFileSync(outputPath, css, "utf8");
console.log(`Wrote ${outputPath} (${css.length} bytes)`);
