import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourcePath = join(__dirname, "../src/utils/updateCSSThemeVars.ts");
const outputPath = join(__dirname, "../src/styles/theme-tokens.css");

function loadColorValues() {
  const source = readFileSync(sourcePath, "utf8");
  const marker = "export const COLOR_VALUES = ";
  const start = source.indexOf(marker);
  const endMarker = "} as const satisfies ColorValues;";
  const end = source.indexOf(endMarker, start);

  if (start === -1 || end === -1) {
    throw new Error("Could not locate COLOR_VALUES in updateCSSThemeVars.ts");
  }

  const objectLiteral = source
    .slice(start + marker.length, end + 1)
    .replace(/\/\/.*$/gm, "");

  // COLOR_VALUES is a plain object literal of string tokens.
  return Function(`"use strict"; return (${objectLiteral});`)();
}

function generateThemeTokensCSS(colorValues) {
  const lines = [
    "/* Generated by scripts/generateThemeTokensCSS.mjs, do not edit by hand. */",
    "/* Source of truth: COLOR_VALUES in src/utils/updateCSSThemeVars.ts */",
    "",
    'html[data-theme="light"] {',
    "  color-scheme: light;",
    "}",
    "",
    'html[data-theme="dark"] {',
    "  color-scheme: dark;",
    "}",
    "",
  ];

  for (const [color, themes] of Object.entries(colorValues)) {
    for (const [theme, tokens] of Object.entries(themes)) {
      lines.push(`html[data-color="${color}"][data-theme="${theme}"] {`);

      for (const [token, value] of Object.entries(tokens)) {
        lines.push(`  --${token}: ${value};`);
      }

      lines.push("}", "");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

const colorValues = loadColorValues();
const css = generateThemeTokensCSS(colorValues);
writeFileSync(outputPath, css, "utf8");
console.log(`Wrote ${outputPath} (${css.length} bytes)`);
