# .github/workflows/deploy.yml

name: Deploy Production Prisma Migrations

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js.
      # Using Node.js 22, as it is the current Long-Term Support (LTS) version.
      # We also enable caching for npm to speed up future builds.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # Step 3: Install project dependencies from package-lock.json
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Prisma Migrate Deploy.
      # This command applies pending migrations to the database.
      # It's safe for production because it will not create new migrations.
      - name: Deploy DB migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
